version: '3.9'

services:

  mysql:
    image: mysql:8.4
    container_name: blog-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blog_app
    ports:
      - "3310:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  minio:
    image: quay.io/minio/minio:latest
    container_name: blog-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: Vinayak@0987654321
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data

  blog-app:
    build: .
    container_name: blog-app
    depends_on:
      - mysql
      - minio
    ports:
      - "8011:8010"

volumes:
  mysql-data:
  minio-data: